name: CI Workflow with Eco-CI Measure

on:
  push:
  pull_request:
  workflow_dispatch: # Enables manual execution

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Build
        run: |
          echo "Running build process..."
          # Your build commands here

      - name: Measure CI Carbon Footprint
        run: |
          curl -sL https://raw.githubusercontent.com/cloud-carbon-footprint/ecoci/main/install.sh | bash
          eco-ci-measure

      - name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
          json-output: true

      - name: Convert JSON to CSV
        if: always()
        run: |
          if [ -f /tmp/eco-ci/total-data.json ]; then
            jq -r '(.[0] | keys_unsorted) as $keys | $keys, map([.[ $keys[] ]])[] | @csv' /tmp/eco-ci/total-data.json > eco_results.csv
          else
            echo "No JSON output found, skipping conversion."
          fi
