name: Examples

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"  # Everyday at 7:00am UTC/11:00pm PST

jobs:

  pytest:
    if: github.repository == 'pyg-team/pytorch_geometric'
    runs-on: ubuntu-latest

    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup packages
        uses: ./.github/actions/setup

      - name: Install main package
        run: |
          pip install .[benchmark]

      - name: Run GCN on Cora
        run: |
          python examples/gcn.py --wandb
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: Run GAT on Cora
        run: |
          python examples/gat.py --wandb
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: Run GIN on MUTAG
        run: |
          python examples/mutag_gin.py --wandb
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: Run GNNExplainer
        run: |
          python examples/explain/gnn_explainer.py

      - name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
          json-output: true

      - name: Convert JSON to CSV
        if: always()
        run: |
          if [ -f /tmp/eco-ci/total-data.json ]; then
            jq -r '(.[0] | keys_unsorted) as $keys | $keys, map([.[ $keys[] ]])[] | @csv' /tmp/eco-ci/total-data.json > eco_results.csv
          else
            echo "No JSON output found, skipping conversion."
          fi
