name: PR Labeler

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:

  assign-labels:
    if: github.repository == 'pyg-team/pytorch_geometric'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement
      - name: Add PR labels
        uses: actions/labeler@v5
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

  assign-author:
    if: github.repository == 'pyg-team/pytorch_geometric'
    runs-on: ubuntu-latest

    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement
      - name: Add PR author
        uses: samspills/assign-pr-to-author@v1.0
        continue-on-error: true
        if: github.event_name == 'pull_request'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
          json-output: true

      - name: Convert JSON to CSV
        if: always()
        run: |
          if [ -f /tmp/eco-ci/total-data.json ]; then
            jq -r '(.[0] | keys_unsorted) as $keys | $keys, map([.[ $keys[] ]])[] | @csv' /tmp/eco-ci/total-data.json > eco_results.csv
          else
            echo "No JSON output found, skipping conversion."
          fi
